### ISSUE TITLE
UOP's TODO list

### ISSUE THREAD

**Issue by TheMezStrikes** [XpRienzo/DragonHeaven#748]
__Things to rework__
- [ ] Emotes
- [ ] Custom Colors 
- [ ] Userlist icons
- [ ] Something else I just forgot what it was

__Things to add__
_nothing atm. freedom!_

__Broken things to fix__
- [x] Bug in github plugin
- Server crashes on load if the rooms specified in config don't exist
- [ ] Bug in roomshop.js
- `require('origindb')` without origindb being installed as a dependency when running `node pokemon-showdown` (I hope @Spandamn or @XpRienzo can take a look at that, should be easy to fix but I wouldn't know how)

**Comment by wh0-cares** [comment]
~prioritize dark mode tbh~
